### PR TITLE
fix(#502): explicit case insensitive matching of filenames

### LINKED ISSUE #502: Override does not work
```
  return require("nvim-web-devicons").setup({override = {Jenkinsfile = {color = "#FF0000", cterm_color = "52", icon = "", name = "Jenkinsfile"}}}})
```

And here it is Jenkinsfile, for instance, showing the default icon:

image

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #502 

I'm always nervous about fixes like this... is this safe @hasecilu ?

### CODE REVIEW

**Comment by hasecilu** [comment]
It seems it's working for the files you mentioned were not working.

image

File: lua/nvim-web-devicons/icons-default.lua [hunk 1]
```diff
@@ -275,12 +275,6 @@ local icons_by_filename = {
     cterm_color = "28",
     name = "Vimrc",
   },
-  ["R"] = {
-    icon = "󰟔",
-    color = "#2266ba",
-    cterm_color = "25",
-    name = "R",
-  },
```
Comment (alex-courtis) [inline lua/nvim-web-devicons/icons-default.lua:283]: This and `r` appear to be incorrectly placed extension.

**Comment by alex-courtis** [comment]
Thanks mate.
