### PR TITLE
fix(#572, #575): ensure icon overrides apply after refresh

### LINKED ISSUE #572: Bug: user icons set from setup are lost after refresh
## First some words...

Hi, first of all, I appreciate a lot this open source plugin, and really, I'm super happy to have a chance to bring some gratitude for all the work from the NeoVim community. That said! Here is the issue...

## Problem
I've realized that this plugin is not applying the icons set by the user by calling to `setup` function (e.g. icons set from `overrides_by_extension`.

I've done some investigation, and I have found that in https://github.com/nvim-tree/nvim-web-devicons/pull/270 pull request, we introduced this auto command, in order to change icons depending on the background:

https://github.com/nvim-tree/nvim-web-devicons/blob/4c3a5848ee0b09ecdea73adcd2a689190aeb728c/lua/nvim-web-devicons.lua#L453-L456

From the issue description [here](https://github.com/nvim-tree/nvim-web-devicons/issues/226), I read:

> I have no config for nvim-web-devicons.

What it makes me think that the functionality was added without verifying that user overrides were kept.

It happens that NeoVim sets the background on startup automatically, as you can see in `:help background`

Image

So just after all plugins are loaded with Lazy, the auto command is executed by NeoVim, loosing all user overrides.

**As result, user icon overrides are not applied ever.**

## Requirement
Apply changes needed so user's icons overrides are kept on background changes (i.e. also applied just after opening NeoVim).

P.D: Hope all this makes sense to you 🙏

### LINKED ISSUE #575: nvim-web-devicons.lua:202: attempt to index upvalue 'user_icons' (a nil v alue)
### Description

Newest commit gives error during nvim start

### Neovim version

```text
% nvim --version
NVIM v0.11.0
Build type: Release
LuaJIT 2.1.1741730670
Run "nvim -V1 -v" for more info
```

### nvim-web-devicons version

09d9caa

### Operating system and version

Pop!_OS 22.04 LTS

### Windows variant

_No response_

### Expected behavior

Empty `:messages` :-)

### Actual behavior

`:messages`:

```
Error detected while processing TermResponse Autocommands for "*"..OptionSet Autocommands for "background":                                  
Error executing lua callback: ...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:202: attempt to index upvalue 'user_icons' (a nil v
alue)                                                                                                                                        
stack traceback:                                                                                                                             
        ...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:202: in function 'apply_user_icons'                                      
        ...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:455: in function <...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons
.lua:453>                                                                                                                                    
        [C]: in function '__newindex'                                                                                                        
        vim/_defaults.lua: in function ''                                                                                                    
        vim/_defaults.lua: in function <vim/_defaults.lua:0>   
```

### PR DESCRIPTION
**Pull request by dsaenztagarro**
Resolves #572 (original issue)
Resolves #575 (reported bug)

### What I did
I reapplied the changes from #572.

In addition, I fixed the reported bug with 37078ee42c620f63d0d3465b39515bec31d81975.

### How to reproduce the bug

I configured locally the plugin so I simulate I "require" the plugin from other plugin as dependency, but without calling "setup". 

```lua
return {
  'nvim-tree/nvim-web-devicons',
  dir="/Users/dsaenz/Code/nvim-web-devicons",
  dev = true,
  config = function()
    require'nvim-web-devicons'
  end
}
```

With this, when I open NeoVim I got exactly the same error reported by the user:

Screenshot 2025-04-07 at 01 38 16

#### Explanation

Because `setup` was not called, `user_icons` was not initialized properly. As result, calling `apply_user_icons` from the auto command was 🧨 .

### CODE REVIEW

File: lua/nvim-web-devicons/filetypes.lua [hunk 1]
```diff
@@ -132,6 +132,7 @@ return {
   ["odin"] = "odin",
   ["openscad"] = "scad",
   ["opus"] = "opus",
+  ["org"] = "org",
```
Comment (alex-courtis) [inline lua/nvim-web-devicons/filetypes.lua:135]: Thank you.

File: lua/nvim-web-devicons.lua [hunk 2]
```diff
@@ -197,39 +198,11 @@ local function get_highlight_ctermfg(icon_data)
...
-
-function M.has_loaded()
-  return loaded
-end
-
-local if_nil = vim.F.if_nil
-function M.setup(opts)
-  if loaded then
+local function apply_user_icons()
+  if type(user_icons) ~= "table" then
```
Comment (alex-courtis) [inline lua/nvim-web-devicons.lua:202]: This is the safest course of action, it maintains existing behaviour.
